# .golangci.yml configuration for Go linting
# This configuration ensures high code quality and consistency

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - third_party
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  funlen:
    lines: 100
    statements: 50
  godox:
    keywords:
      - NOTE
      - OPTIMIZE
      - HACK
  revive:
    min-confidence: 0
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return

linters:
  disable-all: true
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # Additional useful linters
    - asciicheck
    - bodyclose
    - dupl
    - exhaustive
    - exportloopref
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - rowserrcheck
    - revive
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - goconst
        - dupl
        - lll

    # Exclude godox from complaining about TODO comments in tests
    - path: _test\.go
      linters:
        - godox

    # Ignore complexity in test files
    - path: _test\.go
      linters:
        - gocyclo
        - gocognit

    # Allow long lines in test data
    - path: _test\.go
      text: "Line contains"
      linters:
        - lll

    # Exclude certain revive rules for test files
    - path: _test\.go
      text: "should not use dot imports"
      linters:
        - revive

    # Exclude certain rules for main.go
    - path: cmd/server/main\.go
      linters:
        - gochecknoinits

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default-severity: error
  rules:
    - linters:
        - dupl
        - gomnd
        - goconst
      severity: warning